### ISSUE TITLE
phpunit - No coverage driver found

### ISSUE THREAD

**Issue by Gaurav-Punjabi** [kirschbaum-development/laravel-test-runner-container#9]
Hi, I am using this container to test my laravel application. It's working perfectly fine. I'm just having one issue while generating code coverage report for my application.

I need to install xdebug as PHPUnit needs coverage driver to generate coverage reports.

Do you have any solution for this problem ?

Thanks in advance.

**Comment by adammparker** [comment]
Hey @Gaurav-Punjabi!

Instead of using xdebug, I would recommend using `phpdbg` as we've recently added this to the container and it should actually be more performant when running `phpunit` over using xdebug.

The command would look something like this:

`phpdbg -dmemory_limit=1G -qrr vendor/bin/phpunit --coverage-clover tests/coverage/clover.xml --coverage-text`

I've found that you need to specify a higher memory limit as `phpdbg` uses more memory that xdebug, but is _much_ faster, but you can certainly try it first without the `-dmemory_limit` argument if you have a relatively small test suite.

**Comment by luisdalmolin** [comment]
@Gaurav-Punjabi Does this work for you?
